### ISSUE TITLE
Integrating into Node Red RasPi

### ISSUE THREAD

**Issue by Dodgerules** [ncd-io/ncd-red-mcp4725#2]
Can you point me in the right direction. I have tried installing the node via NPM but no new nodes are present in the pallet. I would also ask if there is a source of information for using the js file you have in this repository in Node Red. Thanks you your assistance ahead of time.

**Comment by zaphod-42** [comment]
You need to restart node-red after the installation, on the pi you can run node-red-stop and node-red-start from the command line, then you'll need to reload the flow in your browser. I don't have any documentation for using this outside of node-red, but there is a test.js file that gives an example
